//add contact
export const ADD_CONTACT_START = "ADD_CONTACT_START";

export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";

export const ADD_CONTACT_FAILURE = "ADD_CONTACT_FAILURE";

//fetch contacts
export const FETCH_CONTACTS_START = "FETCH_CONTACTS_START";

export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";

export const FETCH_CONTACTS_FAILURE = "FETCH_CONTACTS_FAILURE";

//delete contacts
export const DELETE_CONTACT_START = "DELETE_CONTACT_START";

export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";

export const DELETE_CONTACT_FAILURE = "DELETE_CONTACT_FAILURE";

//edit contacts
export const EDIT_CONTACT_START = "EDIT_CONTACT_START";

export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS";

export const EDIT_CONTACT_FAILURE = "EDIT_CONTACT_FAILURE";
